### ISSUE TITLE
Draft workshop reviews

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [solliancenet/Solliance_AI_Led_business_process_automation#1]
Please leave review comments for our authors below. Thank you!

**Comment by SidneyPhoon** [comment]
1.  In "https://github.com/solliancenet/Solliance_AI_Led_business_process_automation/blob/main/Hands-on%20lab/Before%20the%20HOL%20-%20AI-led%20business%20process%20automation.md#task-1-provision-a-resource-group",  Step "2 On the Resource groups blade, select **+Add**.".  It should be **+Create**.

**Comment by SidneyPhoon** [comment]
In [Exercise 1, Task 3](https://github.com/solliancenet/Solliance_AI_Led_business_process_automation/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20AI-led%20business%20process%20automation.md#task-3-implementing-forms-recognizer-for-document-processing) , Step 10, opening Visual Studio with the Community Version is not an option.  This is what I see.  
![Visual_Studio_2019_sign_in](https://user-images.githubusercontent.com/31261946/124993998-642a9200-e002-11eb-961e-7002145c2c9f.PNG)

I had to sign-in to continue with the lab.

**Comment by SidneyPhoon** [comment]
In [Exercise 1, Task 5, Step 7](https://github.com/solliancenet/Solliance_AI_Led_business_process_automation/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20AI-led%20business%20process%20automation.md#task-5-running-document-processing-automation)  While in the VM, I am unable to stay logged in to Azure Portal with my Microsoft account.  I get these errors.

![Exe1_Task5_Sign_in_Portal_From_VM](https://user-images.githubusercontent.com/31261946/125000113-e9b33f80-e00c-11eb-8ab4-6a5209480a6f.PNG)

Signing in again gives me an error:
![image](https://user-images.githubusercontent.com/31261946/125000445-a5746f00-e00d-11eb-9454-115a739d0c9c.png)


To workaround this issue, I downloaded the claims forms into my local laptop, login to Azure Portal on my laptop and uploaded the claim forms for the "claims" containers.

**Comment by daronyondem** [comment]
Hi @SidneyPhoon,

Thanks for all the feedback. 

1. The resource creation screenshot and wording are now [updated](https://github.com/solliancenet/Solliance_AI_Led_business_process_automation/commit/05347888be810211ca6a765680a85eba1128bda9).
2. It looks like MS started to enforce MSA login for Community Edition Visual Studio. Users don't have to purchase a license. They can simply log in with an MSA account. I have added the [instructions ](https://github.com/solliancenet/Solliance_AI_Led_business_process_automation/commit/768f2429155a65a043bac04f42e51c64a6f4bd58)to the lab.
3. The sign-in issue you experiences relates to an organizational Azure subscription you are using and how your organization configures [conditional access](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/overview). Your laptop is probably joined to the organizational Active Directory, where a different set of access policy rules apply. That might be why you see different behavior. To prevent issues, [the Microsoft Azure subscription must be pay-as-you-go or MSDN](https://github.com/solliancenet/Solliance_AI_Led_business_process_automation/blob/main/Hands-on%20lab/Before%20the%20HOL%20-%20AI-led%20business%20process%20automation.md#requirements). This is a requirement listed in the [Before HOL Document](https://github.com/solliancenet/Solliance_AI_Led_business_process_automation/blob/main/Hands-on%20lab/Before%20the%20HOL%20-%20AI-led%20business%20process%20automation.md#requirements). 

Thanks for giving the lab a run. I hope you liked it.

**Comment by SidneyPhoon** [comment]
In [exercise 3, task 4, step 7](https://github.com/solliancenet/Solliance_AI_Led_business_process_automation/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20AI-led%20business%20process%20automation.md#task-4-configuring-the-hospital-portal), the names and corresponding value descriptions do not match.
![image](https://user-images.githubusercontent.com/31261946/125136240-aec21200-e0c7-11eb-8b35-624da7eb81a6.png)

**Comment by SidneyPhoon** [comment]
In exercise 3, task 4, step 10, the result is stunning!  But please explain the results, what are those terms highlighted in green?  Are they from the Healthcare entities?  How did you unify the search results from two indexes, how do you unify the search scores from 2 indexes?  These kinds of integration are of greatest interest to our customers, they want to know how it is done.  More details of what goes on behind the scene will be most helpful.

![image](https://user-images.githubusercontent.com/31261946/125137717-7d971100-e0ca-11eb-91c9-6942cba29ca4.png)

**Comment by SidneyPhoon** [comment]
In the [Manual Resource Setup Guide](https://github.com/solliancenet/Solliance_AI_Led_business_process_automation/blob/main/Hands-on%20lab/Manual-resource-setup.md) and other areas of the HOL, it is strange that Azure resources are referred to as "account".  They should be referred to as "resources"

![image](https://user-images.githubusercontent.com/31261946/125141131-5ee84880-e0d1-11eb-88ba-ffbec072d8db.png)

**Comment by zxpek** [comment]
Worked through 4 tasks. Successful completion with no major issues. 

- I like that all resources are made available directly in the provisioned VM. 
- I might highlight further the need to assign permissions when generating SAS in exercise 1, since this instruction is easily missed.
- Had some performance issues running VS in the VM but not a deal breaker since only minor edits needed.
- Would you consider marking the VS parts optional? Since the code edits are not required for lab completion. As Sidney mentioned above, login issues might slow down progress.
- I ran PowerBI desktop from my own device instead of the VM so no comments here.
